baseURL = "http://datawaveproject.github.io/"
languageCode = "en-us"
title = "The DataWave Project"
theme="ananke"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = "G-C7R59RGNK9"
  google_tag_manager_id = ""
  featured_image = '/images/gravity_waves_big.jpg'

 [params.jobs]
    summary_truncate = 12  # How many characters to include in the summary of the team bios (large layout) before truncating

[params.Single]
featured_image = '/images/gravity_waves_big.jpg'



[menu]
  # Main Menu
  #[[menu.main]]
  #  name = "Objectives"
  #  url = "/objectives/"
  #    weight = 1
  # Footer Menu

  [[menu.main]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/Team/"
      weight = 2

  [[menu.main]]
      name = "Jobs"
      url = "/Jobs/"
      weight = 3

  [[menu.main]]
      name = "Background"
      url = "/Background/"
      weight = 4

  [[menu.main]]
      name = "Publications"
      url = "/Publications/"
      weight = 4

  #[[menu.footer]]
  #  name = "Contact"
  #  url = "/contact/"
  #    weight = 2
